version: '3.8'
services:
  dynfiapp:
    image: shley008/dynfi-app:latest
    hostname: dynfiapp
    ports:
      - '9090:9090'
      - '2467:2467'
  dynfidb:
    image: mongo:latest
    hostname: dynfidb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongo-db:/data/db
    ports:
      - '27017:27017'
volumes:
  mongo-db:
    driver: replicated