FROM azul/zulu-openjdk-alpine:18-latest

# Create DIR config
WORKDIR /data/app
COPY dynfi.conf .
COPY dynfi-21.0.10-all.jar .
MKDIR -p /data/conf
RUN mv /data/app/dynfi.conf /data/conf

# Define mountable directories.
VOLUME ["/data/db"]
VOLUME ["/data/conf"]

CMD [ "java", "-jar", "dynfi-21.0.10-all.jar", "--config", "/data/conf/custom.dynfi.conf" ]

#ENTRYPOINT [ "java", "-jar", "/data/app/dynfi-21.0.10-all.jar", "--config", "/data/conf/dynfi.conf" ]