FROM alpine:3.16


RUN \
  echo 'http://dl-cdn.alpinelinux.org/alpine/v3.9/main' >> /etc/apk/repositories && \
  echo 'http://dl-cdn.alpinelinux.org/alpine/v3.9/community' >> /etc/apk/repositories && \
  apk update

# install Mongo
RUN \
  apk update
  apk add mongodb
  apk add mongodb-tools
# Create dir Mongo
RUN mkdir -p /data/db
RUN chown mongodb:mongodb /data/db


# Define mountable directories.
VOLUME ["/data/db"]

CMD [ "mongod" ] 
